<?php

namespace Core\Database\Internal;

use Illuminate\Database\Eloquent\Model as EloquentModel;
use Illuminate\Database\Eloquent\Collection;

/**
 * @internal
 */
abstract class Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<\Illuminate\Database\Eloquent\Model>|null
     */
    protected $model;

    /**
     * The number of models that should be generated.
     *
     * @var int|null
     */
    protected $count;

    /**
     * The state transformations that will be applied to the model.
     *
     * @var array<int, callable|array<string, mixed>>
     */
    protected $states = [];

    final public function __construct()
    {
    }

    /**
     *  Get a new factory instance for the model.
     *
     *  @param  int|null  $count
     *  @param  array<int, callable|array<string, mixed>>  $states
     *  @return static
     */
    public static function new($count = null, $states = [])
    {
        $factory = new static();
        $factory->count = $count;
        $factory->states = $states;

        return $factory;
    }

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    abstract public function definition(): array;

    /**
     * Set the amount of models you wish to create / make.
     *
     * @param  int  $count
     * @return static
     */
    public function count(int $count): static
    {
        $factory = clone $this;
        $factory->count = $count;
        return $factory;
    }

    /**
     * Add a new state transformation to the model definition.
     *
     * @param  callable|array<string, mixed>  $state
     * @return static
     */
    public function state(callable|array $state): static
    {
        $factory = clone $this;
        $factory->states[] = $state;
        return $factory;
    }

    /**
     * Create a collection of models and persist them to the database.
     *
     * @param  array<string, mixed>  $attributes
     * @return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection
     */
    public function create(array $attributes = [])
    {
        $results = $this->make($attributes);

        if ($results instanceof EloquentModel) {
            $results->save();
            return $results;
        }

        $results->each->save();
        return $results;
    }

    /**
     * Create a collection of models.
     *
     * @param  array<string, mixed>  $attributes
     * @return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Collection
     */
    public function make(array $attributes = [])
    {
        if ($this->count === null) {
            return $this->makeInstance($attributes);
        }

        if ($this->count < 1) {
            return new Collection();
        }

        $models = [];
        for ($i = 0; $i < $this->count; $i++) {
            $models[] = $this->makeInstance($attributes);
        }

        return new Collection($models);
    }

    /**
     * Make an instance of the model with the given attributes.
     *
     * @param  array<string, mixed>  $attributes
     * @return \Illuminate\Database\Eloquent\Model
     */
    protected function makeInstance(array $attributes = [])
    {
        return $this->newModel($this->getRawAttributes($attributes));
    }

    /**
     * Get the raw attributes for the model as an array.
     *
     * @param  array<string, mixed>  $attributes
     * @return array<string, mixed>
     */
    protected function getRawAttributes(array $attributes = [])
    {
        $definition = $this->definition();

        foreach ($this->states as $state) {
            if (is_callable($state)) {
                $state = $state($attributes);
            }
            $definition = array_merge($definition, $state);
        }

        return array_merge($definition, $attributes);
    }

    /**
     * Get a new model instance.
     *
     * @param  array<string, mixed>  $attributes
     * @return \Illuminate\Database\Eloquent\Model
     */
    public function newModel(array $attributes = [])
    {
        $model = $this->modelName();

        return new $model($attributes);
    }

    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return string
     */
    public function modelName()
    {
        if ($this->model) {
            return $this->model;
        }

        $name = class_basename(static::class);
        $modelName = str_replace('Factory', '', $name);

        return 'App\\Models\\' . $modelName;
    }
}
